### ISSUE TITLE
function to calculate belt placement

### ISSUE THREAD

**Issue by MichaelRFairhurst** [MichaelRFairhurst/solver_3#1]
have a todo in frame.scad, needs to be filled.

**Comment by IamfromSpace** [comment]
To get the tangent angle (t) for the two gears we use:
`cos(t) = (1-a/b)/d`
a = smaller gear radius
b = larger gear radius
d = distance between the gears

Then with that, we can calculate the belt circumference (c) we can use
`c = 2 * (a*cos(t) + pi - b*cos(t) + sqrt((b*cos(t) - d - a*cos(t))^2 + (b*sin(t) - a*sin(t)^2))`
(half length of the wrapped gears, distance from one tangent point to another)

However, we want to go the other way.... which appears not to be possible based on [this post](https://math.stackexchange.com/questions/123361/distance-between-two-gears-surrounded-by-a-known-length-belt).

Not totally sure I understand the approximation formula provided, since it seems like `B` is partly what we want to approximate in the first place.


This also seems to have [a simpler belt length formula](http://blog.misumiusa.com/sizing-timing-belts-and-pulleys/).
