### ISSUE TITLE
Calculate gap required for cube to spin without hitting the arm

### ISSUE THREAD

**Issue by MichaelRFairhurst** [MichaelRFairhurst/solver_3#9]

**Comment by IamfromSpace** [comment]
Because the claw is "open," it appears that just getting the claw "out of the way" of the cube edges, means it will not make any contact on cube rotation.  This is because if you spin the cube on a point, the maximum radius is the edge of a square.

Given this, the total extension distance needs to be: `extension_tolerance + (layer_count - 1) * layer_width + static_claw_depth`.
